language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpcap0.8-dev
  - sudo pip install cpp-coveralls --use-mirrors
script: autoreconf --install && ./configure --enable-gcov && make && make check
after_success: coveralls --exclude lib --exclude tests
