language: c
compiler:
  - gcc
  - clang
env:
  global:
    - GCOV_EXCLUDE="-e getopt1.c -e getopt.c -e getopt.h -e hash.c -e hash.h -e inet_aton.c -e link-bpf.c -e link-dlpi.c -e obstack.c -e obstack.h -e strlcat.c -e strlcpy.c"
  matrix:
    - GCOV_OPT="--enable-gcov"
    - GCOV_OPT="--disable-gcov"
matrix:
  exclude:
    - compiler: clang
      env: GCOV_OPT="--enable-gcov" 
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpcap0.8-dev
  - sudo pip install cpp-coveralls --use-mirrors
script:
  - autoreconf --install && ./configure $GCOV_OPT && make && make check
after_success:
  - if [ $GCOV_OPT == "--enable-gcov" ]; then coveralls $GCOV_EXCLUDE; fi
